version: "3.8"

services:
  database:
    image: postgres:15
    container_name: telegram_db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: telegram_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: telegram_redis
    restart: always
    ports:
      - "6379:6379"

  controller:
    build: ./controller
    container_name: telegram_controller
    restart: always
    depends_on:
      - database
      - redis
    environment:
      REDIS_HOST: redis
      DB_HOST: database
      DB_NAME: telegram_db
      DB_USER: your_user
      DB_PASSWORD: your_password
    ports:
      - "5001:5001"

  client:
    build: ./client
    container_name: telegram_client
    restart: always
    depends_on:
      - controller
    environment:
      REDIS_HOST: redis
      DB_HOST: database
      DB_NAME: telegram_db
      DB_USER: your_user
      DB_PASSWORD: your_password
    ports:
      - "5002:5002"

  web:
    build: ./web
    container_name: telegram_web
    restart: always
    depends_on:
      - database
      - controller
    environment:
      REDIS_HOST: redis
      DB_HOST: database
      DB_NAME: telegram_db
      DB_USER: your_user
      DB_PASSWORD: your_password
    ports:
      - "8000:8000"

volumes:
  db_data: